### ISSUE TITLE
Program exits with code 0 and does nothing.

### ISSUE THREAD

**Issue by Vexthecollector** [RageAgainstThePixel/OpenAI-DotNet#128]
# Bug Report

## Overview
code used:
```csharp
var api = new OpenAIClient("sk-my.key");
var models = await api.ModelsEndpoint.GetModelsAsync();
foreach (var model in models)
{
    Console.WriteLine(model.ToString());
}
````

when running this code, the program will crash and send an exit code 0. No idea why it would break so hard that it does not even generate an Exception.

**Comment by StephenHodgson** [comment]
@Vexthecollector not really sure why it would crash for you. I was not able to repro this with the code snippet you provided.

I created a new console app with .net7 and imported the project via nuget.

**Comment by StephenHodgson** [comment]
was not able to reproduce

**Comment by nick-zocdoc** [comment]
I had this problem because I put this code inside a Test() method and called it from a non-async Main() method, without an `await`.  So when it hit the async part, it was actually calling it without blocking, so then the Main() method continued to run and exited.  So when calling an async method from a non-async method, you need to do something like `Test().GetAwaiter().GetResult();`.  Then it will block until the value is returned.
