### ISSUE TITLE
Custom Azure OpenAI chat models not working until following model name constraint

### ISSUE THREAD

**Issue by sibbl** [RageAgainstThePixel/OpenAI-DotNet#149]
# Bug Report

## Overview
Now that fine tuning of gpt-3.5-turbo is possible on Azure OpenAI, deployed models can have arbitrary names.
This project however fails to accept models which don't have "turbo" or "gpt-4" in their names. [See these lines of code](https://github.com/RageAgainstThePixel/OpenAI-DotNet/blob/9efcacdb728d57c37d88022e05c9027b142a3e39/OpenAI-DotNet/Chat/ChatRequest.cs#L94C1-L98C14).

## To Reproduce
1. Go to Azure OpenAI
2. Fine tune gpt-3.5-turbo
3. Create a deployment called "foobar"
4. "foobar is not supported" will be thrown.

## Expected behavior
The model "foobar" should be a valid name.

## Workaround
Put "turbo" or "gpt-4" in your custom deployment ids in Azure.

## Additional context
I'd suggest to remove these constraints.

PS: Generally, I'd suggest to open up the configuration of OpenAI endpoints. I'd suggest some generic interface which provides a base URL of the services as well as some interceptors to add custom things like authorization headers.

**Comment by StephenHodgson** [comment]
>  I'd suggest some generic interface which provides a base URL of the services as well as some interceptors to add custom things like authorization headers.

There already is an interface for this, but customizing headers is likely not possible.

> Generally, I'd suggest to open up the configuration of OpenAI endpoints.

sure, but it'd also be nice if MSFT actually conformed to OpenAI endpoint naming standards for their implementation instead of coming up with their own.

TBH I'm half tempted to axe the Azure aspect of the project and suggest you use MSFTs official version.

**Comment by StephenHodgson** [comment]
In the meantime, I suggest using the gpt-3.5-Turbo or gpt-4 names in your trained models

**Comment by isberg** [comment]
I am not 100% sure, but this naming restriction also seems to prevent usage of gpt-3.5-turbo-instruct, which I think should work with the [CompletionsEndpoint](https://github.com/RageAgainstThePixel/OpenAI-DotNet/blob/9efcacdb728d57c37d88022e05c9027b142a3e39/OpenAI-DotNet/Completions/CompletionRequest.cs#L286C1-L290C40).

**Comment by ADefWebserver** [comment]
> TBH I'm half tempted to axe the Azure aspect of the project and suggest you use MSFTs official version.

I was afraid that you would eventually feel this way.

**Comment by StephenHodgson** [comment]
Just don't have enough time and resources, and theirs is auto generated. But I will likely keep is updated as the Unity version of this plugin is what I use much more often.

So as I push fixes there, I push them here. Just gotta focus on client work first, since I don't have enough free time to focus on these projects full time.

**Comment by StephenHodgson** [comment]
So far none of my clients use OpenAI on Azure, but if they do, I'll likely update it faster.

**Comment by StephenHodgson** [comment]
I think it is safe to remove name constraint since the api itself will tell you if it doesn't work

**Comment by StephenHodgson** [comment]
only half done 😅
