### ISSUE TITLE
supporting .netstandar 2

### ISSUE THREAD

**Issue by grammy-work** [RageAgainstThePixel/OpenAI-DotNet#153]
Hi, It's not like a request but a discussion on possibility, is it possible to add support on .net standard 2? I tried and found the only difference is the use of system.text.json instead of newtonsoft. Thanks!

**Comment by StephenHodgson** [comment]
I'm sorry, I made a decision to only support .net 6+

**Comment by HavenDV** [comment]
Hello, we would like to use your library as the main one for LangChain.Providers.OpenAI:
https://github.com/tryAGI/LangChain/tree/main/src/libs/Providers/LangChain.Providers.OpenAI
Previously we were using a client generated from the OpenAPI specification with the addition of generator/helper classes. But due to the abundance of anyOf/oneOf in this specification, its support is now becoming a problem:
https://github.com/tryAGI/OpenAI
Unfortunately, the lack of netstandard is the main blocker to use your library. From my experience, adding netstandard to your project is quite simple (I did it now by copying and adding this directly)
We would add a generator on top for simplified use of functions and auxiliary methods for obtaining constants (model IDs, prices and context lengths)

**Comment by StephenHodgson** [comment]
In my honest opinion Lang Shane is deprecated now that agents is out
